name: Build Backend Docker Image

on:
  push:
    tags:
      - "todo-api-*" # Trigger on tags that start with 'todo-api-'
    branches:
      - master
    paths:
      - "todo-api/**" # Trigger when there are changes in the 'backend' directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for backend
        run: |
          docker build -t your-dockerhub-username/todo:api-${{ github.sha }} ./todo-api
          docker push your-dockerhub-username/todo:api-${{ github.sha }}
